language: cpp

os: osx

script: echo "Hello World" > 1.txt

after_success: prepare_deploy.sh

deploy:
  skip_cleanup: true
  provider: bintray
  file: bintray.json
  user: "stloeffler"
  on:
    all_branches: true
  dry-run: true
