language: cpp

#addons:
#  apt:
##    sources:
##    - ubuntu-sdk-team # for qt5
##    - debian-sid # for poppler-qt5
#    packages:
#    - cmake
#    - libqt4-dev
#    - qtbase5-dev
#    - qtscript5-dev
#    - qttools5-dev
#    - zlib1g-dev
#    - libhunspell-dev
#    - libpoppler-qt4-dev
#    - libpoppler-qt5-dev
#    - libpoppler-private-dev
#    - liblua5.2-dev

matrix:
  include:
    - os: osx
      env: QT=4 TARGET_OS=osx
#    - os: osx
#      env: QT=5 TARGET_OS=osx
    - os: linux
      dist: trusty
      sudo: required
      env: QT=5 TARGET_OS=win
    - os: linux
      dist: trusty
      sudo: required
      env: QT=5 TARGET_OS=linux

before_install:
  - travis-ci/get-dependencies.sh

before_script:
  - . travis-ci/configure.sh

script:
  - cd "${BUILDDIR}" && make VERBOSE=1

before_deploy:
  - if [ $TRAVIS_OS_NAME == osx ]; then cd "${BUILDDIR}" && cpack --verbose; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then cd "${TRAVIS_BUILD_DIR}/build-$TRAVIS_OS_NAME-qt$QT" && ./set_dmg_layout.scpt; ls /Volumes; fi
#  - cd ${TRAVIS_BUILD_DIR} && find .
  - cd ${TRAVIS_BUILD_DIR} && travis-ci/prepare-bintray.sh

deploy:
  skip_cleanup: true
  provider: bintray
  file: travis-ci/bintray.json
  user: stloeffler
  on:
    condition: "$TRAVIS_OS_NAME == osx && $QT == 4"
  key:
    secure: oULH4rfgoSAo46cmFdhTZ4Bse+DWAFke4toShIzDiOoooyXhXkbMU/lDMe5msUXVYejIr4icyuC/9/JkRCLtSYNIgafuLtvCYI+SWF2pyta00NyETDmXrF6tQqtaUVMEpfsozbYVcnMGrEUDCEzKseLgnUPthz7Kr2hvXO2ga6WX/0csiH2Tvr/vwQHM3hz4uck/O+VSEXWt1WvYMbHGd3hnxuzUBSCDorPJNLl/zWs0MgzGepZwFq3NXWUkee0k7G6d1vHotdinShqfdG4pWx/ZJIRFys2R8PYosKx62/1CAdNLfW8bT8lP7h+eape7QlaHqRHkFZrU0wpzqvQdtCnoAibp7ND+44L4iyJAg2XhvKqxp912OaEloLYklx4rsGRPiu408/z304zYG2KRAWwHwn0Ik2JY+oXtfF3lxbD7O/yYG267R8hjq1A9MRiMCd/eXNRZbGhkLoP41eIU1icbowsEgiue6mXLY1vIs68vA4qu5fA5rebfialzfUqpsnvLf5lyCI8eHtOJ825Km002LErcI0ODCFyoqVlk4W2rTwsmQzN4NlU9G4e4HoRxP5TgwzvHyMEzlgz+HGroglR6uqxmrOTBFlSq+4V4xfTXGLLJreC7NtZ2f50pv8GZMH57gt/GoZ9K03n84K0U68rlBH1HydSrQZZ1R2gfkPE=
  dry-run: true
