language: cpp

addons:
  apt:
    sources:
    - ubuntu-sdk-team
    packages:
    - cmake
    - libqt4-dev
    - qtbase5-dev
    - qtscript5-dev
    - qttools5-dev
    - zlib1g-dev
    - libhunspell-dev
    - libpoppler-qt4-dev
    - libpoppler-qt5-dev
    - libpoppler-private-dev
    - liblua5.2-dev

dist: trusty

branches:
  only:
    - master

env:
  - QT=4
  - QT=5

before_script:
  - mkdir build-${QT} && cd build-${QT} && cmake .. -DTW_BUILD_ID='travis-ci' -DCMAKE_INSTALL_PREFIX='/usr' -DDESIRED_QT_VERSION="${QT}"
script:
  - cd build-${QT} && make VERBOSE=1
