language: cpp

matrix:
  include:
#    - name: "Mac OS X (Qt 5)"
#      env: TARGET_OS=osx QT=5
#      os: osx
    - name: "Windows (Qt 5)"
      env: TARGET_OS=win QT=5
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: deb https://pkg.mxe.cc/repos/apt xenial main
              key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0xC6BF758A33A3A276
          packages:
            - mxe-i686-w64-mingw32.static-cairo # poppler dependency
            - mxe-i686-w64-mingw32.static-curl # poppler dependency
            - mxe-i686-w64-mingw32.static-freetype # poppler dependency
            - mxe-i686-w64-mingw32.static-glib # poppler dependency
            - mxe-i686-w64-mingw32.static-hunspell
            - mxe-i686-w64-mingw32.static-jpeg # poppler dependency
            - mxe-i686-w64-mingw32.static-lcms # poppler dependency
            - mxe-i686-w64-mingw32.static-libpng # poppler dependency
            - mxe-i686-w64-mingw32.static-libwebp # poppler dependency
            - mxe-i686-w64-mingw32.static-lua
            - mxe-i686-w64-mingw32.static-openjpeg # poppler dependency
#            - mxe-i686-w64-mingw32.static-poppler
            - mxe-i686-w64-mingw32.static-qtbase # poppler dependency
            - mxe-i686-w64-mingw32.static-qtscript
            - mxe-i686-w64-mingw32.static-qttools
            - mxe-i686-w64-mingw32.static-tiff # poppler dependency
            - mxe-i686-w64-mingw32.static-zlib # poppler dependency
    - name: "Ubuntu/Linux (Qt 5)"
      env: TARGET_OS=linux QT=5
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - ubuntu-dev-tools
            - dput
            - python-paramiko
            - debhelper
            - qtbase5-dev
            - qtscript5-dev
            - qttools5-dev
            - qttools5-dev-tools
            - zlib1g-dev
            - libhunspell-dev
            - libpoppler-qt5-dev
            - libpoppler-private-dev
            - poppler-data
            - liblua5.2-dev
            - fakeroot
    - name: "Ubuntu/Linux (Qt 5) [coverage]"
      env: TARGET_OS=linux QT=5 COVERAGE=ON
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: deb https://pkg.mxe.cc/repos/apt xenial main
              key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0xC6BF758A33A3A276
          packages:
            - mxe-i686-w64-mingw32.static-cairo # poppler dependency
            - mxe-i686-w64-mingw32.static-curl # poppler dependency
            - mxe-i686-w64-mingw32.static-freetype # poppler dependency
            - mxe-i686-w64-mingw32.static-glib # poppler dependency
            - mxe-i686-w64-mingw32.static-hunspell
            - mxe-i686-w64-mingw32.static-jpeg # poppler dependency
            - mxe-i686-w64-mingw32.static-lcms # poppler dependency
            - mxe-i686-w64-mingw32.static-libpng # poppler dependency
            - mxe-i686-w64-mingw32.static-libwebp # poppler dependency
            - mxe-i686-w64-mingw32.static-lua
            - mxe-i686-w64-mingw32.static-openjpeg # poppler dependency
#            - mxe-i686-w64-mingw32.static-poppler
            - mxe-i686-w64-mingw32.static-qtbase # poppler dependency
            - mxe-i686-w64-mingw32.static-qtscript
            - mxe-i686-w64-mingw32.static-qttools
            - mxe-i686-w64-mingw32.static-tiff # poppler dependency
            - mxe-i686-w64-mingw32.static-zlib # poppler dependency

#    - name: "Windows (MSVC)"
#      env: TARGET_OS=win QT=5
#      os: windows



#    - name: "Ubuntu/Linux (Qt 4)"
#      env: TARGET_OS=linux QT=4
#      os: linux
#      addons:
#        apt:
#          packages:
#            - ubuntu-dev-tools
#            - dput
#            - python-paramiko
#            - debhelper
#            - libqt4-dev
#            - zlib1g-dev
#            - libhunspell-dev
#            - libpoppler-qt4-dev
#            - libpoppler-private-dev
#            - poppler-data
#            - liblua5.2-dev
#            - fakeroot
#    - name: "Ubuntu/Linux (Qt 5)"
#      env: TARGET_OS=linux QT=5
#      os: linux
#      addons:
#        apt:
#          packages:
#            - ubuntu-dev-tools
#            - dput
#            - python-paramiko
#            - debhelper
#            - qtbase5-dev
#            - qtscript5-dev
#            - qttools5-dev
#            - qttools5-dev-tools
#            - zlib1g-dev
#            - libhunspell-dev
#            - libpoppler-qt5-dev
#            - libpoppler-private-dev
#            - poppler-data
#            - liblua5.2-dev
#            - fakeroot
#    - name: "Ubuntu/Linux (Qt 5) [coverage]"
#      env: TARGET_OS=linux QT=5 COVERAGE=ON
#      os: linux
#      addons:
#        apt:
#          packages:
#            - qtbase5-dev
#            - qtscript5-dev
#            - qttools5-dev
#            - qttools5-dev-tools
#            - zlib1g-dev
#            - libhunspell-dev
#            - libpoppler-qt5-dev
#            - libpoppler-private-dev
#            - poppler-data
#            - liblua5.2-dev
#            - lcov

before_install:
  - ${TRAVIS_BUILD_DIR}/travis-ci/get-dependencies.sh

before_script:
  - ${TRAVIS_BUILD_DIR}/travis-ci/configure.sh

script:
  - ${TRAVIS_BUILD_DIR}/travis-ci/build.sh
  - ${TRAVIS_BUILD_DIR}/travis-ci/run-tests.sh

after_success:
  - ${TRAVIS_BUILD_DIR}/travis-ci/package.sh

deploy:
  - provider: bintray
    skip_cleanup: true
    file: ${TRAVIS_BUILD_DIR}/travis-ci/bintray.json
    user: stloeffler
    on:
      all_branches: true
      condition: -f ${TRAVIS_BUILD_DIR}/travis-ci/bintray.json
    key:
      secure: oULH4rfgoSAo46cmFdhTZ4Bse+DWAFke4toShIzDiOoooyXhXkbMU/lDMe5msUXVYejIr4icyuC/9/JkRCLtSYNIgafuLtvCYI+SWF2pyta00NyETDmXrF6tQqtaUVMEpfsozbYVcnMGrEUDCEzKseLgnUPthz7Kr2hvXO2ga6WX/0csiH2Tvr/vwQHM3hz4uck/O+VSEXWt1WvYMbHGd3hnxuzUBSCDorPJNLl/zWs0MgzGepZwFq3NXWUkee0k7G6d1vHotdinShqfdG4pWx/ZJIRFys2R8PYosKx62/1CAdNLfW8bT8lP7h+eape7QlaHqRHkFZrU0wpzqvQdtCnoAibp7ND+44L4iyJAg2XhvKqxp912OaEloLYklx4rsGRPiu408/z304zYG2KRAWwHwn0Ik2JY+oXtfF3lxbD7O/yYG267R8hjq1A9MRiMCd/eXNRZbGhkLoP41eIU1icbowsEgiue6mXLY1vIs68vA4qu5fA5rebfialzfUqpsnvLf5lyCI8eHtOJ825Km002LErcI0ODCFyoqVlk4W2rTwsmQzN4NlU9G4e4HoRxP5TgwzvHyMEzlgz+HGroglR6uqxmrOTBFlSq+4V4xfTXGLLJreC7NtZ2f50pv8GZMH57gt/GoZ9K03n84K0U68rlBH1HydSrQZZ1R2gfkPE=
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
      condition: -f ${TRAVIS_BUILD_DIR}/travis-ci/dput-launchpad.sh
    script: sh "${TRAVIS_BUILD_DIR}/travis-ci/dput-launchpad.sh"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: nqZSJsON/RaZL7ApjZw5OvgJ3HIrVm6eCZAJ8HcAukgqALXeG9XMkR2F8oIpGNp+/HVBys/5DoNp6CAyvkI2r1J6TofhQ/JfO7HT/DWJqiDbnSQMUUDuq1j/LwDS/WrM0juGO2tb/ACP40yI+lqqybuuri5iUfjkkfk7y73I6bkqxbT5MrdHWpnC7O73kmTmdGwoLBuIXhw5NQrzfAPgROvmIn+M/MDWhi7+kb31eIufOuu141m0G/Pu4zSAtxHdQ3vYmcvOXIZ9YjtTU0vztjilrUX7DGgpmzkGmlf/KsLvMZ/oAi7MUZvp8k9kTHLvm1YxXGsuta+hNFYCFgmxK8a2dWRHksNDjI9ebmtUw56kNQSdAcqHgH4RO2eWFPJjqVcZbgzT826ku6QoIxqlwaTYpQFb6TBqT9flPiVGT4y7tGKDdTxqSmykSPPiTVlr47tUPYzOK/robR8pdKxpsscvMSgzHGI+k5mxH9rnS2DkyGtUo6Fohe6B4zZYGsbTo+esiI2MgwyVVgcLYft9bqlWiOyLk1OCiLAqO28K4AobnWKL1M6M+hH2bcqTyF2Wzy0pOchxxtt5bkRNc9qAPUoXh9GVbxZIG4KCC5Pt4gOmKxPk3A3aD7ynr9ifDhuyzxttNqMGGqaK6QmlXYh/Iu7aQlRME4ERyQBUUDRqjXU=
    file: "$(cat ${TRAVIS_BUILD_DIR}/travis-ci/github-releases.txt)"
    on:
      tags: true
      condition: -f "${TRAVIS_BUILD_DIR}/travis-ci/github-releases.txt"
      repo: stloeffler/texworks-travis-ci
