language: minimal

addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-luatex
    - tex4ht
    - texlive-fonts-recommended
    - lmodern
    - texlive-lang-french
    - ghostscript
    - imagemagick
    - netpbm
    - ubuntu-dev-tools
    - debhelper
    - dput
    - fakeroot
    - python-paramiko
    - tidy

script:
  - make dist

after_success:
  - ${TRAVIS_BUILD_DIR}/travis-ci/package.sh

deploy:
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
      condition: -f ${TRAVIS_BUILD_DIR}/travis-ci/launchpad/dput-launchpad.sh
    script: sh "${TRAVIS_BUILD_DIR}/travis-ci/launchpad/dput-launchpad.sh"
  - provider: bintray
    skip_cleanup: true
    file: ${TRAVIS_BUILD_DIR}/travis-ci/bintray/bintray.json
    user: stloeffler
    on:
      all_branches: true
      condition: -f ${TRAVIS_BUILD_DIR}/travis-ci/bintray/bintray.json
    key:
      secure: oULH4rfgoSAo46cmFdhTZ4Bse+DWAFke4toShIzDiOoooyXhXkbMU/lDMe5msUXVYejIr4icyuC/9/JkRCLtSYNIgafuLtvCYI+SWF2pyta00NyETDmXrF6tQqtaUVMEpfsozbYVcnMGrEUDCEzKseLgnUPthz7Kr2hvXO2ga6WX/0csiH2Tvr/vwQHM3hz4uck/O+VSEXWt1WvYMbHGd3hnxuzUBSCDorPJNLl/zWs0MgzGepZwFq3NXWUkee0k7G6d1vHotdinShqfdG4pWx/ZJIRFys2R8PYosKx62/1CAdNLfW8bT8lP7h+eape7QlaHqRHkFZrU0wpzqvQdtCnoAibp7ND+44L4iyJAg2XhvKqxp912OaEloLYklx4rsGRPiu408/z304zYG2KRAWwHwn0Ik2JY+oXtfF3lxbD7O/yYG267R8hjq1A9MRiMCd/eXNRZbGhkLoP41eIU1icbowsEgiue6mXLY1vIs68vA4qu5fA5rebfialzfUqpsnvLf5lyCI8eHtOJ825Km002LErcI0ODCFyoqVlk4W2rTwsmQzN4NlU9G4e4HoRxP5TgwzvHyMEzlgz+HGroglR6uqxmrOTBFlSq+4V4xfTXGLLJreC7NtZ2f50pv8GZMH57gt/GoZ9K03n84K0U68rlBH1HydSrQZZ1R2gfkPE=

