language: cpp

matrix:
  include:
#    - name: "Mac OS X (Qt 5)"
#      env: TARGET_OS=osx QT=5
#      os: osx
    - name: "Windows (Qt 5)"
      env: TARGET_OS=win QT=5
      os: linux
      sudo: required
      services: docker
#    - name: "Windows (MSVC)"
#      env: TARGET_OS=win QT=5
#      os: windows



#    - name: "Ubuntu/Linux (Qt 4)"
#      env: TARGET_OS=linux QT=4
#      os: linux
#      addons:
#        apt:
#          packages:
#            - ubuntu-dev-tools
#            - dput
#            - python-paramiko
#            - debhelper
#            - libqt4-dev
#            - zlib1g-dev
#            - libhunspell-dev
#            - libpoppler-qt4-dev
#            - libpoppler-private-dev
#            - poppler-data
#            - liblua5.2-dev
#            - fakeroot
#    - name: "Ubuntu/Linux (Qt 5)"
#      env: TARGET_OS=linux QT=5
#      os: linux
#      addons:
#        apt:
#          packages:
#            - ubuntu-dev-tools
#            - dput
#            - python-paramiko
#            - debhelper
#            - qtbase5-dev
#            - qtscript5-dev
#            - qttools5-dev
#            - qttools5-dev-tools
#            - zlib1g-dev
#            - libhunspell-dev
#            - libpoppler-qt5-dev
#            - libpoppler-private-dev
#            - poppler-data
#            - liblua5.2-dev
#            - fakeroot
#    - name: "Ubuntu/Linux (Qt 5) [coverage]"
#      env: TARGET_OS=linux QT=5 COVERAGE=ON
#      os: linux
#      addons:
#        apt:
#          packages:
#            - qtbase5-dev
#            - qtscript5-dev
#            - qttools5-dev
#            - qttools5-dev-tools
#            - zlib1g-dev
#            - libhunspell-dev
#            - libpoppler-qt5-dev
#            - libpoppler-private-dev
#            - poppler-data
#            - liblua5.2-dev
#            - lcov

before_install:
  - ${TRAVIS_BUILD_DIR}/travis-ci/get-dependencies.sh

before_script:
  - ${TRAVIS_BUILD_DIR}/travis-ci/configure.sh

script:
  - ${TRAVIS_BUILD_DIR}/travis-ci/build.sh
  - ${TRAVIS_BUILD_DIR}/travis-ci/run-tests.sh

after_success:
  - ${TRAVIS_BUILD_DIR}/travis-ci/package.sh

deploy:
  - provider: bintray
    skip_cleanup: true
    file: ${TRAVIS_BUILD_DIR}/travis-ci/bintray.json
    user: stloeffler
    on:
      all_branches: true
      condition: -f ${TRAVIS_BUILD_DIR}/travis-ci/bintray.json
    key:
      secure: oULH4rfgoSAo46cmFdhTZ4Bse+DWAFke4toShIzDiOoooyXhXkbMU/lDMe5msUXVYejIr4icyuC/9/JkRCLtSYNIgafuLtvCYI+SWF2pyta00NyETDmXrF6tQqtaUVMEpfsozbYVcnMGrEUDCEzKseLgnUPthz7Kr2hvXO2ga6WX/0csiH2Tvr/vwQHM3hz4uck/O+VSEXWt1WvYMbHGd3hnxuzUBSCDorPJNLl/zWs0MgzGepZwFq3NXWUkee0k7G6d1vHotdinShqfdG4pWx/ZJIRFys2R8PYosKx62/1CAdNLfW8bT8lP7h+eape7QlaHqRHkFZrU0wpzqvQdtCnoAibp7ND+44L4iyJAg2XhvKqxp912OaEloLYklx4rsGRPiu408/z304zYG2KRAWwHwn0Ik2JY+oXtfF3lxbD7O/yYG267R8hjq1A9MRiMCd/eXNRZbGhkLoP41eIU1icbowsEgiue6mXLY1vIs68vA4qu5fA5rebfialzfUqpsnvLf5lyCI8eHtOJ825Km002LErcI0ODCFyoqVlk4W2rTwsmQzN4NlU9G4e4HoRxP5TgwzvHyMEzlgz+HGroglR6uqxmrOTBFlSq+4V4xfTXGLLJreC7NtZ2f50pv8GZMH57gt/GoZ9K03n84K0U68rlBH1HydSrQZZ1R2gfkPE=
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
      condition: -f ${TRAVIS_BUILD_DIR}/travis-ci/dput-launchpad.sh
    script: sh "${TRAVIS_BUILD_DIR}/travis-ci/dput-launchpad.sh"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: R95GDHMu7wk4TgBv4rkOmib1ZRrKwzC6OUUn4ZQmiRXjG2o8K5snWDsUtakbs+KGkKD/F8TNwlIvOxiacty00JTdzSVQnNXzkdBquv5E4Krj7w3YfC16tBZl7tfqjdf3Wp0ri4D/P79EpS6tpC9A9C6gjn1YYFA7fWvcYGzd2mSUlrB/gI9PUW7Wt66K0ustZnRzp3U51GhbGrq6llUnU3pixxny8B7obgwrj2AC9oWE2jzOghWeJBiG72EZNWFmWdAC3TK5FRKD9fEI9DVOt8rziM7azZKTfdCJn0KUX8jSVqQIgALxaUKRnBpeyvKFpDAtiI5SN4LcFmijfPmc54HJDIDr1SSyR26LcAhbl7/ZvLfpqJPDdwxWvsaEvWpCkksmHdkbzmauCD7SRet+bfUQ1rZejzcI0sdHQG19n6qopi2hFELB+IB7QBRcTBD5V/0ggNr8Pu2a4Ogh8IN3ixbbZ2bPBWJbva9Ui2lU0nfq15dSaHYiqKldFSwMK516UDr8LaURV5SUnT59p1n2C9r+VLe2nkiK3ShF7aERaD/iWfX7Fsq+aXfrHvpA17bGSE/e3ZUL4nRefapJl0MIzSh8RDpyc75uKIXnCodWQckBpCQoslaKphuw7uYjAO9Nypip38G/sdewIuIAI+CiadcOOZvdc3UUUTcdMi2a4G4=
    file: "$(cat ${TRAVIS_BUILD_DIR}/travis-ci/github-releases.txt)"
    on:
      tags: true
      condition: -f "${TRAVIS_BUILD_DIR}/travis-ci/github-releases.txt"
