name: 'Build Poppler'
author: 'Stefan Löffler'
description: 'Build the Poppler PDF rendering library'
inputs:
  version:
    description: 'Which version to build'
    required: true
  install:
    required: false
    description: 'Run sudo make install after build?'
    default: true
  install-deps:
    required: false
    description: 'Whether or not to automatically install dependencies'
    default: true
  poppler-data-version:
    required: false
    description: 'Install the specified version of poppler-data if specified'
    default: undefined
runs:
  using: 'node12'
  main: 'index.js'
