name: CI BigSur
on:
  - push
  - pull_request

jobs:

  build-macosx-bigsur-homebrew:
    name: macOS 11.0 (Homebrew)
    runs-on: macos-11.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        brew update > brew_update.log || { echo "Updating homebrew failed"; cat brew_update.log; exit 1; }
        brew install coreutils hunspell poppler lua qt5

    - name: Configure
      run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: QT_QPA_PLATFORM_PLUGIN_PATH="${Qt5_DIR}/plugins/platforms" ctest -V
      working-directory: build

    - name: Try run
      run: |
        ls -lisa
        find .
        gtimeout 5 ./TeXworks.app
      working-directory: build
