# This is a basic workflow to help you get started with Actions

name: CI (test)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#  build-linux:
#    name: Build on Linux
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    if: false
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#
#    - name: Install Dependencies
#      run: |
#        sudo apt update -y
#        sudo apt install -y qtbase5-dev qtscript5-dev qttools5-dev qttools5-dev-tools zlib1g-dev libhunspell-dev libpoppler-qt5-dev libpoppler-private-dev liblua5.3-dev xvfb
#
#    - name: Configure
#      run: |
#        pwd
#        mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX='/usr' -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE}
#
#    - name: Build
#      run: make -j
#      working-directory: build
#
#    - name: Test
#      run: xvfb-run ctest -V
#      working-directory: build

################################################################################

  build-mxe:
    name: Build for Windows (MXE)
    runs-on: ubuntu-latest
    if: false
    env:
      MXEDIR: /usr/lib/mxe
      MXETARGET: i686-w64-mingw32.static

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        wget -qO - "https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0xC6BF758A33A3A276" | sudo apt-key add -
        sudo add-apt-repository --yes --update "deb https://pkg.mxe.cc/repos/apt xenial main"
        sudo apt install mxe-i686-w64-mingw32.static-cairo mxe-i686-w64-mingw32.static-curl mxe-i686-w64-mingw32.static-freetype mxe-i686-w64-mingw32.static-glib mxe-i686-w64-mingw32.static-hunspell mxe-i686-w64-mingw32.static-jpeg mxe-i686-w64-mingw32.static-lcms mxe-i686-w64-mingw32.static-libpng mxe-i686-w64-mingw32.static-libwebp mxe-i686-w64-mingw32.static-lua mxe-i686-w64-mingw32.static-openjpeg mxe-i686-w64-mingw32.static-poppler mxe-i686-w64-mingw32.static-qtbase mxe-i686-w64-mingw32.static-qtscript mxe-i686-w64-mingw32.static-qttools mxe-i686-w64-mingw32.static-tiff mxe-i686-w64-mingw32.static-zlib
      # FIXME: Build poppler (it changes too often)

    - name: Configure
      run: mkdir build && cd build && ${MXEDIR}/usr/bin/${MXETARGET}-cmake -DTW_BUILD_ID='github' -DCMAKE_INSTALL_PREFIX=install -DPLATFORM_DEPENDENCIES='freetype;harfbuzz_too;freetype;bz2' -DPoppler_ADDITIONAL_DEPENDENCIES='freetype;harfbuzz;freetype_too;glib-2.0;intl;iconv;ws2_32;winmm;tiff;webp;jpeg;openjp2;png;lcms2;lzma;bz2;pcre16;wtsapi32' -DTEXWORKS_ADDITIONAL_LIBS='wtsapi32;opengl32;imm32;shlwapi;dwmapi;uxtheme' ..


    - name: Build
      run: ${MXEDIR}/usr/bin/${MXETARGET}-cmake --build . && ${MXEDIR}/usr/bin/${MXETARGET}-strip TeXworks.exe
      working-directory: build

    - name: Install
      run: ${MXEDIR}/usr/bin/${MXETARGET}-cmake --build build --target install

#    - name: Package tests
#      run: mkdir tests && cp test_*.exe tests/
#      working-directory: build

    - run: find .

    - uses: actions/upload-artifact@v1
      with:
        name: TeXworks-MXE
        path: build/install

#    - uses: actions/upload-artifact@v1
#      with:
#        name: tw-mxe-tests
#        path: build/tests

################################################################################

  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y qtbase5-dev qtscript5-dev qttools5-dev qttools5-dev-tools zlib1g-dev libhunspell-dev libpoppler-qt5-dev libpoppler-private-dev poppler-data liblua5.3-dev xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0

    - name: Configure
      run: |
        mkdir build && cd build && cmake -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE}

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: xvfb-run ctest -V
      working-directory: build

################################################################################

  build-docker:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - distro: Arch Linux
          file: Dockerfile.arch
        - distro: Fedora
          file: Dockerfile.fedora
        - distro: openSUSE
          file: Dockerfile.opensuse
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build -f .github/workflows/${{ matrix.file }} .
