name: Mac Timing
on:
  - push
  - pull_request

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install qtbase5-dev
#    - run: cmake -B build .
#    - run: cmake --build build
#    - run: ./mac-sleep
#      working-directory: build
    - run: /usr/lib/qt5/bin/qmake
    - run: make
    - run: ./mac-sleep


  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install qt5
#    - run: cmake -B build . -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"
#    - run: cmake --build build
#    - run: ./mac-sleep
#      working-directory: build
    - run: /usr/local/opt/qt5/bin/qmake
    - run: make
    - run: mac-sleep.app/Contents/MacOS/mac-sleep

