name: Mac Env

on:
  - push

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y qtbase5-dev xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0

    - name: Configure
      run: cmake -B build ${GITHUB_WORKSPACE}/mac-env

    - name: Build
      run: make
      working-directory: build

    - name: Test
      run: xvfb-run ./mac-env
      working-directory: build

  build-macosx:
    name: Mac OS X
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        brew update > brew_update.log || { print_error "Updating homebrew failed"; cat brew_update.log; exit 1; }
        brew install qt5

    - name: Configure
      run: cmake -B build ${GITHUB_WORKSPACE}/mac-env -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"

    - name: Build
      run: make
      working-directory: build

    - name: Test
      run: open mac-env.app
      working-directory: build
