name: Mac Timing
on:
  - push
  - pull_request

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install qtbase5-dev
    - run: cmake -B build .
    - run: cmake --build build
    - run: ./mac-timing
      working-directory: build

  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install qt5
    - run: cmake -B build .
    - run: cmake --build build
    - run: ./mac-timing
      working-directory: build

