name: MacPorts
on:
  - push
  - pull_request

jobs:
  build-macosx:
    name: Mac OS X
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install MacPorts
      uses: keepitsimpletech/actions/setup-macports@setup-macports/releases/v1

    - run: port version

    - run: port selfupdate

    - run: port install hunspell lua poppler-qt5

    - name: Configure
      run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: QT_QPA_PLATFORM_PLUGIN_PATH="${Qt5_DIR}/plugins/platforms" ctest -V
      working-directory: build

