name: MacPorts
on:
  - push
  - pull_request

jobs:
  build-macosx-macports:
    name: Mac OS X (MacPorts)
    runs-on: macos-10.15
    strategy:
      matrix:
        include:
        - macports-version: 2.6.2
          macports-platform: 10.15-Catalina

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install MacPorts
      run: |
        wget https://github.com/macports/macports-base/releases/download/v${{ matrix.macports-version }}/MacPorts-${{ matrix.macports-version }}-${{ matrix.macports-platform }}.pkg
        sudo /usr/sbin/installer -pkg MacPorts-${{ matrix.macports-version }}-${{ matrix.macports-platform }}.pkg -target /
        echo "::add-path::/opt/local/bin:/opt/local/sbin"

    - name: Install Dependencies
      run: sudo port selfupdate && sudo port install hunspell lua poppler-qt5 qt5-qtbase qt5-qtscript qt5-qttools

    - name: Configure
      run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE}

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: ctest -V
      working-directory: build

