name: MacPorts
on:
  - push
  - pull_request

jobs:
  build-macosx:
    name: Mac OS X
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install MacPorts
      run: |
        wget https://github.com/macports/macports-base/releases/download/v2.6.2/MacPorts-2.6.2-10.15-Catalina.pkg
        sudo /usr/sbin/installer -pkg MacPorts-2.6.2-10.15-Catalina.pkg -target /

    - run: port version

    - run: sudo port selfupdate

    - run: sudo port install hunspell lua poppler-qt5

    - name: Configure
      run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: QT_QPA_PLATFORM_PLUGIN_PATH="${Qt5_DIR}/plugins/platforms" ctest -V
      working-directory: build

