# This is a basic workflow to help you get started with Actions

name: TeXworks CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    name: Build on Linux
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y qtbase5-dev qtscript5-dev qttools5-dev qttools5-dev-tools zlib1g-dev libhunspell-dev libpoppler-qt5-dev libpoppler-private-dev liblua5.3-dev xvfb

    - name: Configure
      run: |
        pwd
        mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX='/usr' -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE}

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: xvfb-run ctest -V
      working-directory: build

  build-win:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtscript'

    - name: Install Dependencies
      run: |
        vcpkg install hunspell lua zlib

    - name: Configure
      run: |
        echo "${{ env.GITHUB_WORKSPACE }}"
        echo "${{ github.workspace }}"
        mkdir build
        cd build
        cmake -DTW_BUILD_ID='github' -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_INSTALLATION_ROOT }}\scripts\buildsystems\vcpkg.cmake ${{ github.workspace }}

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: ctest -V
      working-directory: build

  build-macosx:
    name: Build on Mac OS X
    runs-on: macos-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        brew update > brew_update.log || { print_error "Updating homebrew failed"; cat brew_update.log; exit 1; }
        brew install qt5
        brew install poppler
        brew install hunspell
        brew install lua

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: ctest -V
      working-directory: build
