# This is a basic workflow to help you get started with Actions

name: TeXworks CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#  build-linux:
#    name: Build on Linux
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    if: false
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#
#    - name: Install Dependencies
#      run: |
#        sudo apt update -y
#        sudo apt install -y qtbase5-dev qtscript5-dev qttools5-dev qttools5-dev-tools zlib1g-dev libhunspell-dev libpoppler-qt5-dev libpoppler-private-dev liblua5.3-dev xvfb
#
#    - name: Configure
#      run: |
#        pwd
#        mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX='/usr' -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE}
#
#    - name: Build
#      run: make -j
#      working-directory: build
#
#    - name: Test
#      run: xvfb-run ctest -V
#      working-directory: build

################################################################################

  build-mxe:
    name: Build for Windows (MXE)
    runs-on: ubuntu-latest
    if: false
    env:
      MXEDIR: /usr/lib/mxe
      MXETARGET: i686-w64-mingw32.static

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        wget -qO - "https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0xC6BF758A33A3A276" | sudo apt-key add -
        sudo add-apt-repository --yes --update "deb https://pkg.mxe.cc/repos/apt xenial main"
        sudo apt install mxe-i686-w64-mingw32.static-cairo mxe-i686-w64-mingw32.static-curl mxe-i686-w64-mingw32.static-freetype mxe-i686-w64-mingw32.static-glib mxe-i686-w64-mingw32.static-hunspell mxe-i686-w64-mingw32.static-jpeg mxe-i686-w64-mingw32.static-lcms mxe-i686-w64-mingw32.static-libpng mxe-i686-w64-mingw32.static-libwebp mxe-i686-w64-mingw32.static-lua mxe-i686-w64-mingw32.static-openjpeg mxe-i686-w64-mingw32.static-poppler mxe-i686-w64-mingw32.static-qtbase mxe-i686-w64-mingw32.static-qtscript mxe-i686-w64-mingw32.static-qttools mxe-i686-w64-mingw32.static-tiff mxe-i686-w64-mingw32.static-zlib
      # FIXME: Build poppler (it changes too often)

    - name: Configure
      run: mkdir build && cd build && ${MXEDIR}/usr/bin/${MXETARGET}-cmake -DTW_BUILD_ID='github' -DCMAKE_INSTALL_PREFIX=install -DPLATFORM_DEPENDENCIES='freetype;harfbuzz_too;freetype;bz2' -DPoppler_ADDITIONAL_DEPENDENCIES='freetype;harfbuzz;freetype_too;glib-2.0;intl;iconv;ws2_32;winmm;tiff;webp;jpeg;openjp2;png;lcms2;lzma;bz2;pcre16;wtsapi32' -DTEXWORKS_ADDITIONAL_LIBS='wtsapi32;opengl32;imm32;shlwapi;dwmapi;uxtheme' ..


    - name: Build
      run: ${MXEDIR}/usr/bin/${MXETARGET}-cmake --build . && ${MXEDIR}/usr/bin/${MXETARGET}-strip TeXworks.exe
      working-directory: build

    - name: Install
      run: ${MXEDIR}/usr/bin/${MXETARGET}-cmake --build build --target install

#    - name: Package tests
#      run: mkdir tests && cp test_*.exe tests/
#      working-directory: build

    - run: find .

    - uses: actions/upload-artifact@v1
      with:
        name: TeXworks-MXE
        path: build/install

#    - uses: actions/upload-artifact@v1
#      with:
#        name: tw-mxe-tests
#        path: build/tests

################################################################################

  build-linux:
    name: Linux (Qt ${{ matrix.qt }}, Poppler ${{ matrix.poppler }}, Hunspell ${{ matrix.hunspell }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # The "ancient versions" (with Qt 5.3) are a special case to be included separately
        qt: [5.12.8, 5.15.0]
        disable-warnings: [false]
        include:
          - qt: 5.3
            poppler: 0.24.5
            hunspell: 1.2.8
            poppler-data: 0.4.6
            cmake: 3.1.0
            disable-warnings: true
          - qt: 5.12.8
            poppler: 0.71.0
            hunspell: 1.7.0
            poppler-data: 0.4.9
            cmake: 3.16.2
          - qt: 5.15.0
            poppler: 0.88.0
            hunspell: 1.7.0
            poppler-data: 0.4.9
            cmake: 3.17.2

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Patch out warnings
      if: ${{ matrix.disable-warnings }}
      run: patch -p1 < .github/workflows/no-warnings.patch

    - name: Install Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y zlib1g-dev liblua5.3-dev xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0

    - name: Install CMake
      uses: ./.github/actions/install-cmake
      with:
        version: '${{ matrix.cmake }}'

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '${{ matrix.qt }}'
        modules: 'qtscript'

    - name: Build Poppler
      uses: ./.github/actions/build-poppler
      with:
        version: '${{ matrix.poppler }}'
        poppler-data-version: '${{ matrix.poppler-data }}'

    - name: Build Hunspell
      uses: ./.github/actions/build-hunspell
      with:
        version: '${{ matrix.hunspell }}'

    - name: Version summary
      run: |
        echo "CMake:        $(cmake --version | sed -ne 's/cmake version //p')"
        echo "GCC:          $(gcc --version | sed -ne 's/gcc ([^)]*) //p')"
        echo "Hunspell:     ${{ matrix.hunspell }}"
        echo "Lua:          $(apt-cache policy liblua5.3-dev | sed -ne 's/  Installed: //p')"
        echo "Poppler:      ${{ matrix.poppler }}"
        echo "Poppler-data: ${{ matrix.poppler-data }}"
        echo "Qt:           ${{ matrix.qt }}"
        echo "Zlib:         $(apt-cache policy zlib1g-dev | sed -ne 's/  Installed: //p')"

    - name: Configure
      run: |
        mkdir build && cd build && cmake -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE}

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}" QT_QPA_PLATFORM_PLUGIN_PATH="${Qt5_DIR}/plugins/platforms" xvfb-run ctest -V
      working-directory: build

################################################################################

  build-win:
    name: Windows (Qt ${{ matrix.qt }}, Poppler ${{ matrix.poppler }}, Hunspell ${{ matrix.hunspell }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
#          - qt: 5.12.8
          - qt: 5.14.2 # mingw-w64-x86_64-qt5
            poppler: 0.71.0
            hunspell: 1.7.0
            poppler-data: 0.4.9
            cmake: 3.16.2

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSYS
      uses: numworks/setup-msys2@v1
      with:
        update: true

    - name: Install dependencies
      # git is needed for getting git revision information
      run: msys2do pacman --noconfirm -S git make mingw-w64-x86_64-qt5 mingw-w64-x86_64-gcc mingw-w64-x86_64-lua

    - run: msys2do pacman -Qi mingw-w64-x86_64-qt5

    - name: Install CMake
      uses: ./.github/actions/install-cmake
      with:
        version: '${{ matrix.cmake }}'

#    - name: Install Qt
#      uses: jurplel/install-qt-action@v2
#      with:
#        version: ${{ matrix.qt }}
#        modules: 'qtscript'
#        arch: win64_mingw73

    - name: Build Poppler
      uses: ./.github/actions/build-poppler
      with:
        version: '${{ matrix.poppler }}'
        poppler-data-version: '${{ matrix.poppler-data }}'

    - name: Build Hunspell
      uses: ./.github/actions/build-hunspell
      with:
        version: '${{ matrix.hunspell }}'

    - name: Version summary
      run: |
        msys2do echo `\"CMake:        `$(cmake --version | sed -ne 's/cmake version //p')`\"
        msys2do echo `\"GCC:          `$(gcc --version | sed -ne 's/gcc ([^)]*) //p')`\"
        msys2do echo `\"Hunspell:     ${{ matrix.hunspell }}`\"
        msys2do echo `\"Lua:          `\"
        msys2do echo `\"Poppler:      ${{ matrix.poppler }}`\"
        msys2do echo `\"Poppler-data: ${{ matrix.poppler-data }}`\"
        msys2do echo `\"Qt:           ${{ matrix.qt }}`\"
        msys2do echo `\"Zlib:         `\"

    - name: Configure
      run: msys2do cmake -G `\`"MSYS Makefiles`\`" -B build -DTW_BUILD_ID='github' -DTEXWORKS_ADDITIONAL_LIBS='shlwapi'

    - name: Build
      run: msys2do make -j
      working-directory: build

    - name: Test
      run: msys2do ctest -V
      working-directory: build

  build-macosx:
    name: Mac OS X (Qt ${{ matrix.qt }}, Poppler ${{ matrix.poppler }}, Hunspell ${{ matrix.hunspell }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - qt: 5.12.8
            poppler: 0.71.0
            hunspell: 1.7.0
            poppler-data: 0.4.9
            cmake: 3.16.2
          - qt: 5.15.0
            poppler: 0.88.0
            hunspell: 1.7.0
            poppler-data: 0.4.9
            cmake: 3.17.2

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        brew update > brew_update.log || { print_error "Updating homebrew failed"; cat brew_update.log; exit 1; }
        brew install lua

    - run: brew list --versions lua
    - run: brew info lua
    - run: brew list --versions zlib

    - name: Install CMake
      uses: ./.github/actions/install-cmake
      with:
        version: '${{ matrix.cmake }}'

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        modules: 'qtscript'

    - name: Build Poppler
      uses: ./.github/actions/build-poppler
      with:
        version: '${{ matrix.poppler }}'
        poppler-data-version: '${{ matrix.poppler-data }}'

    - name: Build Hunspell
      uses: ./.github/actions/build-hunspell
      with:
        version: '${{ matrix.hunspell }}'

    - name: Version summary
      run: |
        echo "CMake:        $(cmake --version | sed -ne 's/cmake version //p')"
        echo "GCC:          $(gcc --version | sed -ne 's/gcc ([^)]*) //p')"
        echo "Hunspell:     ${{ matrix.hunspell }}"
        echo "Lua:          $(brew list --versions lua | sed -ne 's/lua //p')"
        echo "Poppler:      ${{ matrix.poppler }}"
        echo "Poppler-data: ${{ matrix.poppler-data }}"
        echo "Qt:           ${{ matrix.qt }}"
        echo "Zlib:         $(brew list --versions zlib | sed -ne 's/zlib //p')"

    - name: Configure
      run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: QT_QPA_PLATFORM_PLUGIN_PATH="${Qt5_DIR}/plugins/platforms" ctest -V
      working-directory: build
