# This is a basic workflow to help you get started with Actions

name: Windows

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: docker version
    - run: |
        $Env:DOCKER_CLI_EXPERIMENTAL="enabled"
        docker version

    - run: sc qc docker

    - run: sc config docker binPath= `"\`"C:\Program Files\Docker\dockerd.exe\`" --run-service --experimental`"
    - run: sc qc docker
    - run: docker version

    - run: Restart-Service docker
    - run: Start-Sleep -Seconds 2
    - run: docker version
#    - run: Get-Content -Path C:\ProgramData\Docker\config\daemon.json -Raw
#    - run: sc start Docker --experimental
#    - run: sc config Docker experimental=enabled
#    - run: docker version

    - name: Build
      run: |
        $Env:DOCKER_CLI_EXPERIMENTAL="enabled"
        docker build --platform linux -t "tw" -f .github/workflows/mxe.docker .

# docker build -t 'tw' -f .github/workflows/Dockerfile .
# docker create --name tw tw
# docker cp tw:/tw/build .
