# This is a basic workflow to help you get started with Actions

name: Windows

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: docker version
    - run: |
        Set-Variable -Name DOCKER_CLI_EXPERIMENTAL -Value enabled
        docker version
#    - run: Get-Content -Path C:\ProgramData\Docker\config\daemon.json -Raw
    - run: sc start Docker --experimental
    - run: docker version

    - name: Build
      run: DOCKER_CLI_EXPERIMENTAL=enabled docker build --platform linux -t "tw" -f .github/workflows/mxe.docker .

# docker build -t 'tw' -f .github/workflows/Dockerfile .
# docker create --name tw tw
# docker cp tw:/tw/build .
