name: Screenshot
on:
  push:
  workflow_dispatch:

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install gnome-screenshot

    - name: Take Screenshot
      run: gnome-screenshot -f /tmp/screenshot.png

    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
        name: Screenshot
        path: /tmp/screenshot.png
