name: Test
on:
  - push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch the entire history so we can create the changelog

    - name: Package for Launchpad
      id: package
      uses: ./.github/actions/package-launchpad
      with:
        DEB_PASSPHRASE: ${{ secrets.DEB_PASSPHRASE }}
        DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}

    - name: Deploy to Launchpad
      uses: ./.github/actions/deploy-launchpad
      with:
        changes_files: ${{ steps.package.outputs.changes_files }}
        devel-repo: "ppa:st.loeffler/test"
        stable-repo: "ppa:st.loeffler/test"

################################################################################

  wsl-test:
    runs-on: windows-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup WSL
      uses: Vampire/setup-wsl@v1
      with:
        additional-packages: apt-transport-https ca-certificates dirmngr

    - name: Install Dependencies
      shell: wsl-bash {0}
      run: |
        echo "deb https://pkg.mxe.cc/repos/apt stretch main" | sudo tee -a /etc/apt/sources.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C6BF758A33A3A276
        sudo apt update
        sudo apt install --assume-yes mxe-i686-w64-mingw32.static-qtbase

        MXEDIR=/usr/lib/mxe
        MXETARGET=i686-w64-mingw32.static
        sudo rm -f "${MXEDIR}/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.d/ccache.cmake"

    - name: Build
      shell: wsl-bash {0}
      working-directory: test
      run: |
        mkdir build && cd build
        /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-cmake ..
        make

    - name: Run
      working-directory: test/build
      shell: bash
      run: |
        pwd
        ls
        export QT_FORCE_STDERR_LOGGING=1
        ./tst.exe
        echo "OK"

################################################################################

  wsl:
    name: WSL
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup WSL
      uses: Vampire/setup-wsl@v1
      with:
        additional-packages: apt-transport-https ca-certificates dirmngr git

    - name: Install Dependencies
      shell: wsl-bash {0}
      run: |
        echo "::group::Install MXE"
        echo "deb https://pkg.mxe.cc/repos/apt stretch main" | sudo tee -a /etc/apt/sources.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C6BF758A33A3A276
        sudo apt update
        sudo apt install --assume-yes libgdk-pixbuf2.0-dev lzip mxe-i686-w64-mingw32.static-cairo mxe-i686-w64-mingw32.static-curl mxe-i686-w64-mingw32.static-freetype mxe-i686-w64-mingw32.static-glib mxe-i686-w64-mingw32.static-hunspell mxe-i686-w64-mingw32.static-jpeg mxe-i686-w64-mingw32.static-lcms mxe-i686-w64-mingw32.static-libpng mxe-i686-w64-mingw32.static-libwebp mxe-i686-w64-mingw32.static-lua mxe-i686-w64-mingw32.static-openjpeg mxe-i686-w64-mingw32.static-qtbase mxe-i686-w64-mingw32.static-qtdeclarative mxe-i686-w64-mingw32.static-qtscript mxe-i686-w64-mingw32.static-qttools mxe-i686-w64-mingw32.static-tiff mxe-i686-w64-mingw32.static-zlib

        MXEDIR=/usr/lib/mxe
        MXETARGET=i686-w64-mingw32.static
        sudo chmod --recursive a+w ${MXEDIR}
        rm -f "${MXEDIR}/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.d/ccache.cmake"
        echo "::endgroup::"

        echo "::group::Build poppler"
        rm -f ${MXEDIR}/src/poppler*
        cp ci/travis-ci/mxe/poppler* ${MXEDIR}/src/
        cd ${MXEDIR}
        make download-only-poppler
        make build-only-poppler_${MXETARGET}
        echo "::endgroup::"

    - name: Configure
      shell: wsl-bash {0}
      run: |
        mkdir build && cd build
        /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-cmake -DTW_BUILD_ID='github' .. \
          -DPLATFORM_DEPENDENCIES='freetype;harfbuzz;freetype_too;bz2;iphlpapi;ssl;crypto;crypt32;ws2_32' \
          -DPoppler_ADDITIONAL_DEPENDENCIES='freetype;harfbuzz;freetype_too;glib-2.0;intl;iconv;ws2_32;winmm;tiff;webp;jpeg;openjp2;png;lcms2;lzma;bz2;pcre16;wtsapi32' \
          -DTEXWORKS_ADDITIONAL_LIBS='freetype;harfbuzz;freetype_too;bz2;wtsapi32;opengl32;imm32;shlwapi;dwmapi;uxtheme' \
          -Dgp_tool='none'
        if [ -f "CMakeFiles/CMakeError.log" ]; then
          echo "=== CMake Error Log ==="
          cat "CMakeFiles/CMakeError.log"
        fi

    - name: Build
      shell: wsl-bash {0}
      run: make VERBOSE=1
      working-directory: build

    - name: Package
      shell: wsl-bash {0}
      id: package
      run: |
        TOPDIR=$(pwd)

        echo "::group::Determine version info"
        # NB: On Windows, there might be a stray \r at the end!
        TW_VERSION=$(sed -ne 's/^#define TEXWORKS_VERSION[[:space:]]"\([0-9.]\{3,\}\)"[[:space:]]*$/\1/p' src/TWVersion.h)
        echo "TW_VERSION = ${TW_VERSION}"
        GIT_HASH=$(git --git-dir=".git" show --no-patch --pretty="%h")
        echo "GIT_HASH = ${GIT_HASH}"
        DATE_HASH=$(date -u +"%Y%m%d%H%M")
        echo "DATE_HASH = ${DATE_HASH}"
        VERSION="${TW_VERSION}-${DATE_HASH}-git_${GIT_HASH}"
        echo "VERSION = ${VERSION}"
        echo "::set-output name=version::${VERSION}"
        echo "::endgroup::"

        echo "::group::Strip TeXworks.exe"
        /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-strip --strip-all build/TeXworks.exe
        echo "::endgroup::"

        echo "::group::Assemble package"
        mkdir -p package-zip/share
        cp build/TeXworks.exe package-zip/
        cp COPYING package-zip/
        cp -r win32/fonts package-zip/share/
        cp -r ci/travis-ci/README.win package-zip/README.txt
        echo "::endgroup::"

        # FIXME: Manual for releases

        echo "::group::Fetch poppler-data"
        POPPLERDATA_VERSION="0.4.10"
        POPPLERDATA_SUBDIR="poppler-data-${POPPLERDATA_VERSION}"
        POPPLERDATA_FILE="poppler-data-${POPPLERDATA_VERSION}.tar.gz"
        POPPLERDATA_URL="https://poppler.freedesktop.org/${POPPLERDATA_FILE}"
        POPPLERDATA_SHA256="6e2fcef66ec8c44625f94292ccf8af9f1d918b410d5aa69c274ce67387967b30"
        wget "${POPPLERDATA_URL}"
        CHKSUM=$(openssl dgst -sha256 "${POPPLERDATA_FILE}" 2> /dev/null)
        if [ "${CHKSUM}" != "SHA256(${POPPLERDATA_FILE})= ${POPPLERDATA_SHA256}" ]; then
          echo "::error::Wrong poppler-data checksum {CHKSUM} (expected: ${POPPLERDATA_SHA256})"
          exit 1
        fi
        echo "::endgroup::"

        echo "::group::Extracting poppler-data"
        tar -xf "${POPPLERDATA_FILE}"
        cd "${POPPLERDATA_SUBDIR}"
        make install prefix="${TOPDIR}/package-zip"
        # Cleanup unused pkgconfig data
        rm -rf "${TOPDIR}/package-zip/share/pkgconfig"
        # Install to build (required for testing)
        make install prefix="${TOPDIR}/build"
        cd "${TOPDIR}"
        echo "::endgroup::"

        # Fixme: installer for releases

        echo "::group::Bundle zip archive"
        cd package-zip && zip -r "${TOPDIR}/TeXworks-win-${VERSION}.zip" *
        echo "::set-output name=file::TeXworks-win-${VERSION}.zip"
        cd "${TOPDIR}"
        echo "::endgroup::"

        echo "::group::Checksums"
        echo "MD5"
        md5sum TeXworks-win-${VERSION}.zip
        echo "SHA256"
        sha256sum TeXworks-win-${VERSION}.zip
        echo "::endgroup::"

    - name: Prepare testing
      shell: wsl-bash {0}
      run: |
        echo "::group::Fixup CTest files"
        SRC=$(pwd)
        DST=$(echo "${{ github.workspace }}" | tr '\\' '/')
        cd build
        for FILE in $(find . -name CTestTestfile.cmake); do
          echo "Fixing $FILE"
          sed -ie "s|${SRC}|${DST}|g" "$FILE"
        done
        echo "::endgroup::"

    - name: Test
      run: ctest -V
      working-directory: build
      env:
        QT_FORCE_STDERR_LOGGING: 1

    - name: Deploy to Bintray
      uses: ./.github/actions/deploy-bintray
      with:
          file: ${{ steps.package.outputs.file }}
          subject: stloeffler
          repo: generic
          pkg: Latest-TeXworks-Win
          version: ${{ steps.package.outputs.version }}
          username: stloeffler
          key: ${{ secrets.bintray_key }}

################################################################################

  win:
    name: Windows
    runs-on: windows-latest
    if: false
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-cmake make mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5-static sed
#        install: mingw-w64-x86_64-cmake git make mingw-w64-x86_64-gcc mingw-w64-x86_64-hunspell mingw-w64-x86_64-lua mingw-w64-x86_64-poppler mingw-w64-x86_64-qt5

    - name: Configure
      run: cmake -G 'MSYS Makefiles' -B build
      working-directory: test

    - name: Build
      run: make -j VERBOSE=1
      working-directory: test/build

    - run: objdump -x test.exe | sed -ne 's/\s*DLL Name:\s+//p'
      working-directory: test/build

    - name: Strip
      run: strip test.exe
      working-directory: test/build

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: test/build/test.exe

    - run: find /mingw64/bin/ -iname '*.dll'

################################################################################

  macos:
    name: Mac OS X (Homebrew)
    runs-on: macos-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: mkdir build

    - name: Package
      id: package
      uses: ./.github/actions/package-macos

    - run: echo "${{ steps.package.outputs.file }}"
