name: Test
on:
  - push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch the entire history so we can create the changelog

    - name: Package for Launchpad
      id: package
      uses: ./.github/actions/package-launchpad
      with:
        DEB_PASSPHRASE: ${{ secrets.DEB_PASSPHRASE }}
        DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}

    - name: Deploy to Launchpad
      uses: ./.github/actions/deploy-launchpad
      with:
        changes_files: ${{ steps.package.outputs.changes_files }}
        devel-repo: "ppa:st.loeffler/test"
        stable-repo: "ppa:st.loeffler/test"

################################################################################

  wsl:
    name: WSL
    runs-on: windows-latest

    steps:
      - uses: Vampire/setup-wsl@v1
        with:
#          update: true
          additional-packages: apt-transport-https
# software-properties-common for add-apt-repository

      - shell: wsl-bash {0}
        run: |
          echo "add-apt-repository"
          echo 'deb https://pkg.mxe.cc/repos/apt stretch main' | sudo tee -a /etc/apt/sources.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C6BF758A33A3A276
          echo "apt search"
          apt search qtbase
          sudo apt update
          echo "apt search"
          apt search qtbase
          sudo apt install mxe-i686-w64-mingw32.static-qtbase
          MXEDIR="/usr/lib/mxe"
          MXETARGET=i686-w64-mingw32.static
          pwd
          ls /mnt
          echo "${{ github.workspace }}"
          cd "/mnt/${{ github.workspace }}/test"
          ${MXEDIR}/usr/bin/${MXETARGET}-cmake -B build
          cd build
          make
          ls


################################################################################

  win:
    name: Windows
    runs-on: windows-latest
    if: false
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-cmake make mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5-static sed
#        install: mingw-w64-x86_64-cmake git make mingw-w64-x86_64-gcc mingw-w64-x86_64-hunspell mingw-w64-x86_64-lua mingw-w64-x86_64-poppler mingw-w64-x86_64-qt5

    - name: Configure
      run: cmake -G 'MSYS Makefiles' -B build
      working-directory: test

    - name: Build
      run: make -j VERBOSE=1
      working-directory: test/build

    - run: objdump -x test.exe | sed -ne 's/\s*DLL Name:\s+//p'
      working-directory: test/build

    - name: Strip
      run: strip test.exe
      working-directory: test/build

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: test/build/test.exe

    - run: find /mingw64/bin/ -iname '*.dll'

################################################################################

  macos:
    name: Mac OS X (Homebrew)
    runs-on: macos-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: mkdir build

    - name: Package
      id: package
      uses: ./.github/actions/package-macos

    - run: echo "${{ steps.package.outputs.file }}"
