name: Test
on:
  - push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch the entire history so we can create the changelog

    - name: Package for Launchpad
      id: package
      uses: ./.github/actions/package-launchpad
      with:
        DEB_PASSPHRASE: ${{ secrets.DEB_PASSPHRASE }}
        DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}

    - name: Deploy to Launchpad
      uses: ./.github/actions/deploy-launchpad
      with:
        changes_files: ${{ steps.package.outputs.changes_files }}
        devel-repo: "ppa:st.loeffler/test"
        stable-repo: "ppa:st.loeffler/test"

################################################################################

  wsl:
    name: WSL
    runs-on: windows-latest

    steps:
      - run: wsl -l
      - run: wsl -l --all
      - run: wsl -l -v
      - run: wsl -l
      - run: wsl sudo apt update

################################################################################

  win:
    name: Windows
    runs-on: windows-latest
    if: false
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-cmake make mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5-static sed
#        install: mingw-w64-x86_64-cmake git make mingw-w64-x86_64-gcc mingw-w64-x86_64-hunspell mingw-w64-x86_64-lua mingw-w64-x86_64-poppler mingw-w64-x86_64-qt5

    - name: Configure
      run: cmake -G 'MSYS Makefiles' -B build
      working-directory: test

    - name: Build
      run: make -j VERBOSE=1
      working-directory: test/build

    - run: objdump -x test.exe | sed -ne 's/\s*DLL Name:\s+//p'
      working-directory: test/build

    - name: Strip
      run: strip test.exe
      working-directory: test/build

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: test/build/test.exe

    - run: find /mingw64/bin/ -iname '*.dll'

################################################################################

  macos:
    name: Mac OS X (Homebrew)
    runs-on: macos-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: mkdir build

    - name: Package
      id: package
      uses: ./.github/actions/package-macos

    - run: echo "${{ steps.package.outputs.file }}"
