name: Test
on:
  - push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch the entire history so we can create the changelog

    - name: Package for Launchpad
      id: package
      uses: ./.github/actions/package-launchpad
      with:
        DEB_PASSPHRASE: ${{ secrets.DEB_PASSPHRASE }}
        DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}

    - name: Deploy to Launchpad
      uses: ./.github/actions/deploy-launchpad
      with:
        changes_files: ${{ steps.package.outputs.changes_files }}
        devel-repo: "ppa:st.loeffler/test"
        stable-repo: "ppa:st.loeffler/test"

################################################################################

  wsl-test:
    runs-on: windows-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup WSL
      uses: Vampire/setup-wsl@v1
      with:
        additional-packages: apt-transport-https ca-certificates dirmngr

    - name: Install Dependencies
      shell: wsl-bash {0}
      run: |
        echo "deb https://pkg.mxe.cc/repos/apt stretch main" | sudo tee -a /etc/apt/sources.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C6BF758A33A3A276
        sudo apt update
        sudo apt install --assume-yes mxe-i686-w64-mingw32.static-qtbase

        MXEDIR=/usr/lib/mxe
        MXETARGET=i686-w64-mingw32.static
        sudo rm -f "${MXEDIR}/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.d/ccache.cmake"

    - name: Build
      shell: wsl-bash {0}
      working-directory: test
      run: |
        mkdir build && cd build
        /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-cmake ..
        make

    - name: Run
      working-directory: test/build
      shell: bash
      run: |
        pwd
        ls
        export QT_FORCE_STDERR_LOGGING=1
        ./tst.exe
        echo "OK"

################################################################################

  wsl:
    name: WSL
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: .github/actions/setup-windows

    - name: Configure
      shell: wsl-bash {0}
      run: |
        mkdir build && cd build
        /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-cmake -DTW_BUILD_ID='github' .. \
          -DPLATFORM_DEPENDENCIES='freetype;harfbuzz;freetype_too;bz2;iphlpapi;ssl;crypto;crypt32;ws2_32' \
          -DPoppler_ADDITIONAL_DEPENDENCIES='freetype;harfbuzz;freetype_too;glib-2.0;intl;iconv;ws2_32;winmm;tiff;webp;jpeg;openjp2;png;lcms2;lzma;bz2;pcre16;wtsapi32' \
          -DTEXWORKS_ADDITIONAL_LIBS='freetype;harfbuzz;freetype_too;bz2;wtsapi32;opengl32;imm32;shlwapi;dwmapi;uxtheme' \
          -Dgp_tool='none'
        if [ -f "CMakeFiles/CMakeError.log" ]; then
          echo "=== CMake Error Log ==="
          cat "CMakeFiles/CMakeError.log"
        fi

    - name: Build
      shell: wsl-bash {0}
      run: make VERBOSE=1
      working-directory: build

    - name: Package
      uses: .github/actions/package-windows
      id: package

    - name: Prepare testing
      shell: wsl-bash {0}
      run: |
        echo "::group::Fixup CTest files"
        SRC=$(pwd)
        DST=$(echo "${{ github.workspace }}" | tr '\\' '/')
        cd build
        for FILE in $(find . -name CTestTestfile.cmake); do
          echo "Fixing $FILE"
          sed -ie "s|${SRC}|${DST}|g" "$FILE"
        done
        echo "::endgroup::"

    - name: Test
      run: ctest -V
      working-directory: build
      env:
        QT_FORCE_STDERR_LOGGING: 1

    - name: Deploy to Bintray
      uses: ./.github/actions/deploy-bintray
      with:
          file: ${{ steps.package.outputs.file }}
          subject: stloeffler
          repo: generic
          pkg: Latest-TeXworks-Win
          version: ${{ steps.package.outputs.version }}
          username: stloeffler
          key: ${{ secrets.bintray_key }}

################################################################################

  win:
    name: Windows
    runs-on: windows-latest
    if: false
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-cmake make mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5-static sed
#        install: mingw-w64-x86_64-cmake git make mingw-w64-x86_64-gcc mingw-w64-x86_64-hunspell mingw-w64-x86_64-lua mingw-w64-x86_64-poppler mingw-w64-x86_64-qt5

    - name: Configure
      run: cmake -G 'MSYS Makefiles' -B build
      working-directory: test

    - name: Build
      run: make -j VERBOSE=1
      working-directory: test/build

    - run: objdump -x test.exe | sed -ne 's/\s*DLL Name:\s+//p'
      working-directory: test/build

    - name: Strip
      run: strip test.exe
      working-directory: test/build

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: test/build/test.exe

    - run: find /mingw64/bin/ -iname '*.dll'

################################################################################

  macos:
    name: Mac OS X (Homebrew)
    runs-on: macos-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: mkdir build

    - name: Package
      id: package
      uses: ./.github/actions/package-macos

    - run: echo "${{ steps.package.outputs.file }}"
