name: Test
on:
  - push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch the entire history so we can create the changelog

    - name: Prepare for packaging
      run: |
        echo "::group::Install dependencies"
        sudo apt install ubuntu-dev-tools debhelper dput
        echo "::endgroup::"
        echo "::group::Import signing keys"
        echo "::group::Setup"
        mkdir -p "${HOME}/.gnupg"
        chmod 700 "${HOME}/.gnupg"
        echo "::endgroup::"
        echo "::group::Import"
        echo '${{ secrets.DECRYPTION_KEY }}' | gpg --quiet --batch --yes --decrypt --passphrase-fd=0 ./.github/actions/package-launchpad/launchpad/key.asc.gpg | gpg --batch --import
        echo "::endgroup::"
        echo "::endgroup::"

    - name: Package for Launchpad
      uses: ./.github/actions/package-launchpad
      with:
        DEB_PASSPHRASE: ${{ secrets.DEB_PASSPHRASE }}

################################################################################

  win:
    name: Windows
    runs-on: windows-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Bintray deploy
      uses: ./.github/actions/deploy-bintray
      with:
          file: COPYING
          subject: stloeffler
          repo: generic
          pkg: test
          version: 4
          username: stloeffler
          key: ${{ secrets.bintray_key }}

################################################################################

  macos:
    name: Mac OS X (Homebrew)
    runs-on: macos-latest
    if: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: mkdir build

    - name: Package
      id: package
      uses: ./.github/actions/package-macos

    - run: echo "${{ steps.package.outputs.file }}"
