name: Workflow
on: push

jobs:
  win:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: windows.jpg

  mac:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: mac.jpg

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install imagemagick
      - uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: linux.jpg
